### Retrieve all todos
GET http://localhost:3000/todos/

### Retrieve by ID
GET http://localhost:3000/todos/debbdb6e-3b65-4195-9517-bcd4404de7c8

### Create a todo
POST http://localhost:3000/todos/
Content-Type: application/json

{
  "title": "My todo",
  "description": "My todo description"
}

### Update a todo
PUT http://localhost:3000/todos/41a3c867-1e83-449c-856a-0c6549a943ff
Content-Type: application/json

{
  "description": "My todo description!!!"
}

### Update a todo
PUT http://localhost:3000/todos/41a3c867-1e83-449c-856a-0c6549a943ff
Content-Type: application/json

{
  "title": "My todo title"
}

### Delete a todo
DELETE http://localhost:3000/todos/debbdb6e-3b65-4195-9517-bcd4404de7c8
