### Retrieve all todos
GET http://localhost:3000/todos/

### Retrieve a todo
GET http://localhost:3000/todos/1

### Create a todo
POST http://localhost:3000/todos/
Content-Type: application/json

{
  "title": "My todo",
  "description": "My todo description"
}

### Retrieve by uuid
GET http://localhost:3000/todos/41a3c867-1e83-449c-856a-0c6549a943ff

### Update a todo
PUT http://localhost:3000/todos/41a3c867-1e83-449c-856a-0c6549a943ff
Content-Type: application/json

{
  "description": "My todo description!!!"
}

### Update a todo
PUT http://localhost:3000/todos/41a3c867-1e83-449c-856a-0c6549a943ff
Content-Type: application/json

{
  "title": "My todo title"
}

### Delete a todo
DELETE http://localhost:3000/todos/41a3c867-1e83-449c-856a-0c6549a943ff
